app:
  env: development
  name: buff
  address: :8018

logging:
  name: admin
  driver: rotate
  level: debug
  file_name: ./log/auth/admin_rotate.log
  file_size_mb:
  max_age:
  max_backups:

jaeger:
  host: 127.0.0.1
  port: 6831
  name: mail-jaeger

jwt:
  secret: xAiNXbZxVdDLerE27Gx3bcjEQNIWvPgrYm0fb3fyKlEsCAuiFvzzBckUbyDzPl21
  ttl: 864000

mysql:
  database: go_mall
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  max_open_conn: 1000
  max_idle_conn: 100
  max_life_second: 30
  max_life_time: 1800
  log_file_name: ./log/admin/sql.log
  table_prefix: