app:
  env: development
  name: go-mall-member
  address: :8081

mysql:
  database: go_mall
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  max_open_conn: 1000
  max_idle_conn: 100
  max_life_second: 30
  max_life_time: 1800
  table_prefix:

logging:
  name: member
  driver: rotate
  level: debug
  file_name: ./log/member/rotate.log
  file_size_mb:
  max_age:
  max_backups: